[package]
name = "sinuous"
version = "0.1.0"
authors = ["Antoine Busch <antoine.busch@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1", features=["cargo"] }
crossterm ={ version = "0.23.1", features=["event-stream"] }
futures = "0.3.21"
sonor = "1.1.0"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }

[dependencies.tui]
version = "0.17.0"
default-features = false
features = ["crossterm"]
