[package]
name = "sinuous"
version = "0.1.6"
edition = "2024"
description = "A simple TUI for controlling local Sonos speakers"
homepage = "https://github.com/abusch/sinuous"
repository = "https://github.com/abusch/sinuous.git"
license = "MIT"

[dependencies]
anyhow = "1.0.57"
clap = { version = "4.6", features = ["cargo"] }
crossterm = { version = "0.29", features = ["event-stream"] }
futures = "0.3.21"
human-panic = "2.0.0"
ratatui = "0.30.0"
rustls = {
  version = "0.23.45",
  default-features = false,
  features = [
    "aws_lc_rs",
    "std",
  ]
}
sinuous-client = { path = "../sonos-ws", version = "0.1.0" }
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.34"
tracing-appender = "0.2.2"
tracing-subscriber = {
  version = "0.3.11",
  features = [
    "env-filter",
    "tracing-log",
  ]
}

[profile.release]
strip = "symbols"
