name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Checking ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux, macos, windows]
        include:
          - build_target: linux
            os: ubuntu-latest
            artifact_suffix: linux-x86_64
            target: x86_64-unknown-linux-gnu
            features: ''
          - build_target: macos
            os: macos-latest
            artifact_suffix: macos-x86_64
            target: x86_64-apple-darwin
            features: ''
          - build_target: windows
            os: windows-latest
            artifact_suffix: windows-x86_64
            target: x86_64-pc-windows-msvc
            features: ''
    steps:
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Checkout src
        uses: actions/checkout@v4
      - name: Running cargo check
        run: cargo check --locked --release --target ${{ matrix.target }} ${{ matrix.features }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt check
        uses: actions-rust-lang/rustfmt@v1
